# Generated by Django 6.0.4 on 2026-04-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolution_comment',
            field=models.TextField(blank=True),
        ),
    ]
