# Generated by Django 6.0.4 on 2026-04-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_resolution_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_pt',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
