# Generated by Django 6.0.4 on 2026-05-12 17:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_category_name_pt"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="tracking_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
