# Generated by Django 6.0.4 on 2026-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_report_tracking_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="address",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
