# Generated by Django 6.0.4 on 2026-04-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Community Portal', help_text='Displayed in the browser tab title and footer.', max_length=100)),
                ('site_tagline', models.CharField(default='Report issues in your community', help_text='Short tagline shown in meta descriptions / SEO.', max_length=255)),
                ('navbar_brand_text', models.CharField(default='Community Portal', help_text='Brand name shown in the top navigation bar.', max_length=100)),
                ('navbar_cta_text', models.CharField(default='New Report', help_text='Label for the primary call-to-action button in the navbar.', max_length=60)),
                ('hero_title', models.CharField(default='Make Your Community Better', help_text='Large heading displayed in the home page hero area.', max_length=255)),
                ('hero_subtitle', models.CharField(default='Help us improve your neighborhood. Report issues, track progress, and stay informed about local improvements.', help_text='Subtitle paragraph below the hero heading.', max_length=500)),
                ('hero_cta_text', models.CharField(default='Submit a Report', help_text='Label for the hero call-to-action button.', max_length=60)),
                ('empty_state_title', models.CharField(default='No reports found', help_text='Heading shown when the reports list is empty.', max_length=255)),
                ('empty_state_body', models.CharField(default='Be the first to report an issue in your area.', help_text='Body text shown when the reports list is empty.', max_length=500)),
                ('about_title', models.CharField(default='About Community Portal', help_text='Heading for the About page.', max_length=255)),
                ('about_body', models.TextField(default='Community Portal is a community-driven platform designed to bridge the gap between citizens and local authorities. By providing a transparent and easy-to-use interface for reporting infrastructure, safety, and environmental issues, we empower residents to take an active role in improving their neighborhoods.', help_text='Main body text for the About page (max 5 000 characters).', max_length=5000)),
                ('footer_copyright_text', models.CharField(blank=True, default='', help_text='Optional extra copyright or legal text shown in the footer. The year and site name are appended automatically.', max_length=255)),
                ('detail_official_response_label', models.CharField(default='Official Response', help_text='Heading for the resolution-comment card on the report detail page.', max_length=100)),
                ('detail_support_title', models.CharField(default='Need Help?', help_text='Heading for the support card on the report detail page.', max_length=100)),
                ('detail_support_body', models.CharField(default='If you have more information about this issue, please contact our community support team.', help_text='Body text for the support card on the report detail page.', max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
