# Generated by Django 6.0.4 on 2026-04-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_body_pt',
            field=models.TextField(default='O Portal Comunitário é uma plataforma impulsionada pela comunidade projetada para aproximar cidadãos e autoridades locais. Ao fornecer uma interface transparente e fácil de usar para relatar problemas de infraestrutura, segurança e ambientais, capacitamos os residentes a desempenharem um papel ativo na melhoria dos seus bairros.', help_text='[PT] Texto principal para a página Sobre.', max_length=5000),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title_pt',
            field=models.CharField(default='Sobre o Portal Comunitário', help_text='[PT] Título para a página Sobre.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_official_response_label_pt',
            field=models.CharField(default='Resposta Oficial', help_text='[PT] Título para o cartão de comentário de resolução.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_support_body_pt',
            field=models.CharField(default='Se tiver mais informações sobre este problema, entre em contacto com a nossa equipa de apoio comunitário.', help_text='[PT] Texto para o cartão de suporte.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='detail_support_title_pt',
            field=models.CharField(default='Precisa de Ajuda?', help_text='[PT] Título para o cartão de suporte.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='empty_state_body_pt',
            field=models.CharField(default='Seja o primeiro a relatar um problema na sua área.', help_text='[PT] Texto exibido quando a lista de relatos está vazia.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='empty_state_title_pt',
            field=models.CharField(default='Nenhum relato encontrado', help_text='[PT] Título exibido quando a lista de relatos está vazia.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_text_pt',
            field=models.CharField(blank=True, default='', help_text='[PT] Texto opcional de copyright ou legal exibido no rodapé.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_text_pt',
            field=models.CharField(default='Submeter Relato', help_text='[PT] Rótulo para o botão de ação do hero.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle_pt',
            field=models.CharField(default='Ajude-nos a melhorar o seu bairro. Relate problemas, acompanhe o progresso e mantenha-se informado sobre melhorias locais.', help_text='[PT] Parágrafo de subtítulo abaixo do cabeçalho hero.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title_pt',
            field=models.CharField(default='Torne a Sua Comunidade Melhor', help_text='[PT] Título grande exibido na área hero da página inicial.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_brand_text_pt',
            field=models.CharField(default='Portal Comunitário', help_text='[PT] Nome da marca exibido na barra de navegação superior.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_cta_text_pt',
            field=models.CharField(default='Novo Relato', help_text='[PT] Rótulo para o botão de ação principal na barra de navegação.', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_pt',
            field=models.CharField(default='Portal Comunitário', help_text='[PT] Apresentado no título do separador do navegador e no rodapé.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_tagline_pt',
            field=models.CharField(default='Relate problemas na sua comunidade', help_text='[PT] Slogan curto exibido nas meta descrições / SEO.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_body',
            field=models.TextField(default='Community Portal is a community-driven platform designed to bridge the gap between citizens and local authorities. By providing a transparent and easy-to-use interface for reporting infrastructure, safety, and environmental issues, we empower residents to take an active role in improving their neighborhoods.', help_text='[EN] Main body text for the About page.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='About Community Portal', help_text='[EN] Heading for the About page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='detail_official_response_label',
            field=models.CharField(default='Official Response', help_text='[EN] Heading for resolution-comment card.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='detail_support_body',
            field=models.CharField(default='If you have more information about this issue, please contact our community support team.', help_text='[EN] Body text for the support card.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='detail_support_title',
            field=models.CharField(default='Need Help?', help_text='[EN] Heading for support card.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='empty_state_body',
            field=models.CharField(default='Be the first to report an issue in your area.', help_text='[EN] Body text shown when the reports list is empty.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='empty_state_title',
            field=models.CharField(default='No reports found', help_text='[EN] Heading shown when the reports list is empty.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='', help_text='[EN] Optional extra copyright or legal text shown in the footer.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta_text',
            field=models.CharField(default='Submit a Report', help_text='[EN] Label for the hero call-to-action button.', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default='Help us improve your neighborhood. Report issues, track progress, and stay informed about local improvements.', help_text='[EN] Subtitle paragraph below the hero heading.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Make Your Community Better', help_text='[EN] Large heading displayed in the home page hero area.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_brand_text',
            field=models.CharField(default='Community Portal', help_text='[EN] Brand name shown in the top navigation bar.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='navbar_cta_text',
            field=models.CharField(default='New Report', help_text='[EN] Label for the primary call-to-action button in the navbar.', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Community Portal', help_text='[EN] Displayed in the browser tab title and footer.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_tagline',
            field=models.CharField(default='Report issues in your community', help_text='[EN] Short tagline shown in meta descriptions / SEO.', max_length=255),
        ),
    ]
