# Generated by Django 6.0.4 on 2026-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0002_sitesettings_about_body_pt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="", help_text="Email address where contact form submissions are sent.", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="privacy_body",
            field=models.TextField(
                blank=True, default="", help_text="[EN] Privacy policy body text.", max_length=10000
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="privacy_body_pt",
            field=models.TextField(
                blank=True, default="", help_text="[PT] Texto do corpo da política de privacidade.", max_length=10000
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="terms_body",
            field=models.TextField(
                blank=True, default="", help_text="[EN] Terms of service body text.", max_length=10000
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="terms_body_pt",
            field=models.TextField(
                blank=True, default="", help_text="[PT] Texto do corpo dos termos de serviço.", max_length=10000
            ),
        ),
    ]
